CREATE TABLE CLIENT
(
	CLIENTID INT NOT NULL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	ADDRESS VARCHAR(255) NOT NULL
);

CREATE TABLE ACCOUNT
(
	ACCOUNTID INT NOT NULL PRIMARY KEY,
	CREATEDATE DATE NOT NULL,
	BALANCE DOUBLE NOT NULL,
	CLIENTID INT,
   FOREIGN KEY(CLIENTID) REFERENCES CLIENT(CLIENTID)
);